language: python
python:
  - 3.6

script:
  - python --version
  - pip install -r build_requirements.txt -r requirements.txt -r test_requirements.txt

  - python setup.py sdist --formats=gztar
  - python setup.py bdist
  - python setup.py bdist_wheel
  - pytest --verbose test

  - ./integration_test.sh
